# Generated by Django 5.0 on 2024-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('slug', models.TextField(verbose_name='slug')),
                ('content', models.TextField(verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='статус публикации')),
                ('views_count', models.IntegerField(blank=True, null=True, verbose_name='кол-во просмотров')),
            ],
            options={
                'verbose_name': 'сообщение блога',
                'verbose_name_plural': 'сообщения блога',
                'ordering': ('title',),
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='last_modified_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
