# Generated by Django 5.0 on 2024-02-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_products_version_delete_category_delete_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='название')),
                ('slug', models.TextField(verbose_name='slug')),
                ('content', models.TextField(verbose_name='контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True, verbose_name='статус публикации')),
                ('views_count', models.IntegerField(blank=True, null=True, verbose_name='кол-во просмотров')),
            ],
            options={
                'verbose_name': 'сообщение блога',
                'verbose_name_plural': 'сообщения блога',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='изображение')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('price_per_unit', models.IntegerField(verbose_name='цена за единицу')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('last_modified_date', models.DateField(verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='version',
            options={},
        ),
        migrations.RemoveField(
            model_name='version',
            name='is_current_version',
        ),
        migrations.AddField(
            model_name='version',
            name='current_version',
            field=models.CharField(default='1.0.0', max_length=100, verbose_name='version number'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_name',
            field=models.CharField(max_length=200, verbose_name='version name'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.CharField(default='1.0.0', max_length=100, verbose_name='version number'),
        ),
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='product'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='client name')),
                ('contact_email', models.EmailField(max_length=254)),
                ('comment', models.TextField(null=True, verbose_name='comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.post', verbose_name='post id')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='product id')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
